name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/genai-core:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/genai-core:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/genai-core:buildcache,mode=max
    
    # Para ambiente AWS EC2 com Docker j치 instalado
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Puxa a imagem mais recente
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/genai-core:latest
          
          # Para o container existente se houver
          docker stop genai-api || true
          docker rm genai-api || true
          
          # Cria diret칩rio persistente para uploads
          mkdir -p /home/ec2-user/genai/uploads
          
          # Executa o container com as vari치veis de ambiente e volumes necess치rios
          docker run -d \
            --name genai-api \
            -p 8000:8000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -v /home/ec2-user/genai/uploads:/app/uploads \
            --restart unless-stopped \
            ${{ secrets.DOCKER_HUB_USERNAME }}/genai-core:latest
            
          echo "Deployment completed successfully"