name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /home/deploy
            if [ ! -d "genai-core/.git" ]; then
              rm -rf genai-core
              git clone git@github.com:paulohenriquevn/genai-core.git genai-core
            fi
            cd genai-core
            git reset --hard origin/main
            git pull origin main

            if [ ! -f "Dockerfile" ]; then
              echo "Erro: Dockerfile não encontrado!"
              exit 1
            fi

            docker build --no-cache -t genai-core:latest .
            docker stop genai-core || true
            docker rm genai-core || true
            docker run -d --name genai-core -p 8000:8000 genai-core:latest
